### ISSUE TITLE
v1.0 Feedback (Apr 10, 2018)

### ISSUE THREAD

**Issue by thawsitt** [thawsitt/philologic_webapp#3]
### Rowan's questions:

1) Could we change the website title to: Local Ecclesiastical Legislation, 1200-1500 (beta)

2) Record title is currently formatted as "Paris (#1284)   [ 1205 ]" ; could it instead be formatted as "Paris, 1205 [ID:1284] "
(I might tweak this further, depending on how it ends up looking... but I think this version will be clearer)

3) The last of the sort options is currently "Year, Classification, Origin Place"; could it instead be "Year, Origin Place, Classification"?

4) This might be harder, but at the moment, the section numbering system ends up being a bit redundant in that it reads e.g. "Capitulum 44 (44)". So if I run a search, the resulting text box might look like:

```
beneficii. Et si convictus fuerit, absque misericordia degradabitur. Capitulum 44 (44) De restitutione rerum ablatarum. In furto, rapina, usura, fraude, ...
```

Is there a way to hide "Capitulum 44" so that it can be used to structure the text, but doesn't display in the text itself? (That's true even for the view that shows the full text.) Or, if it is easier, would it possible to hide the (44) instead?

5) Many of the "Notes" fields are in fact blank - i.e. there is just a placeholder number ([1] [2] [3]...) with no accompanying note. Is it possible to write the parser such that if the number in brackets is not followed by anything, it is omitted altogether? As a further step, if the Notes field is empty OR consists only of numbers in brackets (or [...], which also exists as a placeholder), can it also be omitted from the table of contents display (just like the incipit/explicit sections)?

**Comment by thawsitt** [comment]
### Thawsitt's response:

1. Yes.

2. The year at the end (i.e `[1205]`) is automatically appended by PhiloLogic. You can see similar examples in other projects [here](https://artflsrv03.uchicago.edu/philologic4/bibbleue/query?report=bibliography&method=proxy&start=0&end=0). I can change the text before the year to any format you want, but the year will always be the end because it is PhiloLogic's default.

3. Yes, definitely! (Let me know if you want to add/remove other sorting options. You can choose one or a set of any metadata you want.)

4. I noticed the redundancy but I kept it that way to make sure the section parser works as intended. (It works for most cases, but I noticed [one instance](http://192.64.116.38/philologic/xmltest2/navigate/105/2/2/) where capitulum 1 is parsed as incipit. There might be others, and it will be hard to notice/debug this when I remove `(1)` part.)

    - To directly answer your question, it is not possible to remove `Capitulum 4` since it is section header, but I can remove `(4)` from text during the parsing process.

5. I can remove blank "Footnotes" sections. These are the cases I have in mind:
 - when it is empty (no text at all)
 - when it just says "None"
- when it only contains ... like this:
```
[1] ...
[2] ...
```

Are there any additional cases I should look out for?

Follow-up questions for 5: 

- When I remove the footnotes section in above cases, will [1] [2] [3] remain in the text? If so, wouldn't it be confusing for the reader when he finds [1] in text but there is no footnotes section?

**Comment by rwdorin** [comment]
1) Great
2) For now, then, perhaps let's hide the Record ID altogether from the text, such that it would read only Paris [ 1205 ] . If this ends up causing problems, we can revisit it later. But the RecordID is really only for structural purposes, and is meaningless to most users.
3) Let's add Diocese, Province, and Country to the sorting options.
4) I see your point about catching parser errors - but presumably the Incipit case is the only one that is likely to cause such difficulties. So let's leave the redundancy for now, and maybe return to it later.
4a) It would be good to figure out what is causing that incipit problem. Thank goodness we kept the header search field, since it allowed me to generate a list of all those that have this same problem:
Record ID 0904: [http://192.64.116.38/philologic/xmltest2/navigate/28/2/2/?byte=3571]
Record ID 1498: [http://192.64.116.38/philologic/xmltest2/navigate/65/2/2/?byte=3400]
Record ID 1510: [http://192.64.116.38/philologic/xmltest2/navigate/100/2/2/?byte=3321]
Record ID 0049: [http://192.64.116.38/philologic/xmltest2/navigate/105/2/2/?byte=3535]
Record ID 0036: [http://192.64.116.38/philologic/xmltest2/navigate/160/2/2/?byte=3329]
Record ID 0570: [http://192.64.116.38/philologic/xmltest2/navigate/200/2/2/?byte=3556]
Record ID 0971: [http://192.64.116.38/philologic/xmltest2/navigate/252/2/2/?byte=3818]
Record ID 0244: [http://192.64.116.38/philologic/xmltest2/navigate/289/2/2/?byte=3660]
Can you try to figure out why the parser isn't handling these correctly, since clearly there's something going on here...
5) Your list of cases looks good. 
5a) If the footnotes are blank, there won't be a corresponding entry in the text; it's an artifact of the template that my RA's used, which gave blank [1] [2] [3] [...] in the Notes field for them to fill in.

**Comment by thawsitt** [comment]
1. N/A

2. I can do that.

3. Do you want 3 options or just 1 option `(Diocese, Province, and Country)`?

4. Thanks for catching the errors. I will debug this and once they are all correct, I will remove duplicate section numbers i.e `(44)`

5. Thanks for clarifying. I will update my scripts to remove empty footnotes.

**Comment by rwdorin** [comment]
3. 3 options

**Comment by thawsitt** [comment]
Implemented 1 to 4. I will do 5 and other features before the 18th.
